version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: jaydip
      POSTGRES_PASSWORD: 121212
    volumes:
      - postgres:/var/lib/postgresql/data 

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/LocalEvents-Docker
    ports:
      - "3000:3000"
    depends_on:
      - db 
volumes:
  postgres:      
